/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senacead.jpa.exemplo.gui;

import com.senacead.jpa.exemplo.model.Livro;
import com.senacead.jpa.exemplo.model.LivroJPA;
import javax.swing.JOptionPane;


/**
 *
 * @author tiluc
 */
public class LivroCadastro extends javax.swing.JFrame {

    /**
     * Creates new form LivroCadastro
     */
    public LivroCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LidoGrupo = new javax.swing.ButtonGroup();
        Cabecalho = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Descricao = new javax.swing.JLabel();
        SairBotao = new javax.swing.JButton();
        Formulario = new javax.swing.JPanel();
        TituloTexto = new javax.swing.JLabel();
        TituloCampo = new javax.swing.JTextField();
        AutorTexto = new javax.swing.JLabel();
        AutorCampo = new javax.swing.JTextField();
        EditoraTexto = new javax.swing.JLabel();
        EditoraCampo = new javax.swing.JTextField();
        DataTexto = new javax.swing.JLabel();
        DataCampo = new javax.swing.JTextField();
        DataExemplo = new javax.swing.JLabel();
        LidoTexto = new javax.swing.JLabel();
        LidoSim = new javax.swing.JRadioButton();
        LidoNao = new javax.swing.JRadioButton();
        SalvarBotao = new javax.swing.JButton();
        LimparBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Cadastro de livros");

        Descricao.setText("Preencha os campos abaixo corretamente para realizar o cadastro de um livro:");

        SairBotao.setText("Sair");
        SairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CabecalhoLayout = new javax.swing.GroupLayout(Cabecalho);
        Cabecalho.setLayout(CabecalhoLayout);
        CabecalhoLayout.setHorizontalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SairBotao)
                .addContainerGap())
        );
        CabecalhoLayout.setVerticalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(SairBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descricao)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Formulario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloTexto.setLabelFor(TituloCampo);
        TituloTexto.setText("Titulo:");

        TituloCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloCampoActionPerformed(evt);
            }
        });

        AutorTexto.setText("Autor:");

        AutorCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorCampoActionPerformed(evt);
            }
        });

        EditoraTexto.setText("Editora:");

        DataTexto.setText("Data de Publicação:");

        DataCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataCampoActionPerformed(evt);
            }
        });

        DataExemplo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        DataExemplo.setText("Exemplo: 20/10/2023");

        LidoTexto.setText("Você leu esse livro?");

        LidoGrupo.add(LidoSim);
        LidoSim.setText("Sim");

        LidoGrupo.add(LidoNao);
        LidoNao.setText("Não");

        SalvarBotao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SalvarBotao.setText("Salvar");
        SalvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBotaoActionPerformed(evt);
            }
        });

        LimparBotao.setText("Limpar");
        LimparBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormularioLayout = new javax.swing.GroupLayout(Formulario);
        Formulario.setLayout(FormularioLayout);
        FormularioLayout.setHorizontalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataExemplo)
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloTexto)
                            .addComponent(DataTexto)
                            .addComponent(DataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormularioLayout.createSequentialGroup()
                                .addComponent(LidoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LidoNao))
                            .addComponent(LidoTexto)
                            .addGroup(FormularioLayout.createSequentialGroup()
                                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AutorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AutorTexto))
                                .addGap(45, 45, 45)
                                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditoraTexto)
                                    .addComponent(EditoraCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(LimparBotao)
                        .addGap(18, 18, 18)
                        .addComponent(SalvarBotao)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        FormularioLayout.setVerticalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloTexto)
                    .addComponent(AutorTexto)
                    .addComponent(EditoraTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AutorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditoraCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataTexto)
                    .addComponent(LidoTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LidoSim)
                    .addComponent(LidoNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataExemplo)
                .addGap(36, 36, 36)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarBotao)
                    .addComponent(LimparBotao))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloCampoActionPerformed

    private void AutorCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorCampoActionPerformed

    private void DataCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataCampoActionPerformed

    private void LimparBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparBotaoActionPerformed
        // TODO add your handling code here:
        TituloCampo.setText("");
        AutorCampo.setText("");
        EditoraCampo.setText("");
        DataCampo.setText("");
    }//GEN-LAST:event_LimparBotaoActionPerformed

    private void SalvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBotaoActionPerformed
        // TODO add your handling code here:
        
        Livro l = new Livro();
        
        l.setTitulo(TituloCampo.getText());
        l.setAutor(AutorCampo.getText());
        l.setEditora(EditoraCampo.getText());
        l.setDataPublicacao(Livro.converterParaFormatoBanco(DataCampo.getText()));
        
        if (LidoSim.isSelected()) {
            l.setLido(true);
        } else if (LidoNao.isSelected()) {
            l.setLido(false);
        } else {
            l.setLido(false);
        }
        
        LivroJPA.cadastrar(l);
        JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
    }//GEN-LAST:event_SalvarBotaoActionPerformed

    private void SairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairBotaoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SairBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutorCampo;
    private javax.swing.JLabel AutorTexto;
    private javax.swing.JPanel Cabecalho;
    private javax.swing.JTextField DataCampo;
    private javax.swing.JLabel DataExemplo;
    private javax.swing.JLabel DataTexto;
    private javax.swing.JLabel Descricao;
    private javax.swing.JTextField EditoraCampo;
    private javax.swing.JLabel EditoraTexto;
    private javax.swing.JPanel Formulario;
    private javax.swing.ButtonGroup LidoGrupo;
    private javax.swing.JRadioButton LidoNao;
    private javax.swing.JRadioButton LidoSim;
    private javax.swing.JLabel LidoTexto;
    private javax.swing.JButton LimparBotao;
    private javax.swing.JButton SairBotao;
    private javax.swing.JButton SalvarBotao;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TituloCampo;
    private javax.swing.JLabel TituloTexto;
    // End of variables declaration//GEN-END:variables
}
